name: Run
on:
  # Schedule updates (each 15 minutes)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  freegameviewer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Run Code
        env:
          appKey: ${{ secrets.APPKEY }}
          appSecret: ${{ secrets.APPSECRET }}
          accessToken: ${{ secrets.ACCESSTOKENT }}
          accessSecret: ${{ secrets.ACCESSSECRET }}
          clientId: ${{ secrets.CLIENTID }}
          clientSecret: ${{ secrets.CLIENTSECRET }}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm i
      - run: node index.js
